routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
 */

Route::get('/hola', 'PrimeraController@prueba');

Route::resource('solicitud', 'WebController');

Route::resource('usuario', 'UserController');

Auth::routes();

Route::get('/', 'HomeController@index')->name('home');

app/User.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 
        'apellidopat', 
        'apellidomat',
        'telefono',
        'curp',
        'email', 
        'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function index()
    {
        return view('home');
    }
}

app/Http/Controllers/PrimeraController.php
<?php

namespace App\Http\Controllers;

use App\Http\Controllers\Controller;

class PrimeraController extends Controller
{
    public function prueba(){
        return "Hola soy la web";
    }
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use App\User;
use Illuminate\Http\Request;

class UserController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        return view('users.edit', compact('id'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $user              = User::find($id);
        $user->name        = $request->name;
        $user->apellidopat = $request->apellidopat;
        $user->apellidomat = $request->apellidomat;
        $user->email       = $request->email;
        $user->curp        = $request->curp;
        $user->telefono    = $request->telefono;
        $user->save();

        return redirect()->route('home')->with('flash', 'Sus datos Editados Satisfactoriamente.');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

app/Http/Controllers/WebController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class WebController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return ("welcome");
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('formulario.solicitudMedia');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/formulario/solicitudMedia.blade.php
@extends ('layouts.formatos')

@section('htmlGen')

@section('Contenido')

@endsection

resources/views/home.blade.php
@extends('layouts.app')


@section('content')



<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header"><h1>Información personal</h1></div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif
                    
                     @if(session('flash'))
                    <div class="alert alert-success" role="alert">
                     <strong>Aviso</strong> {{session('flash')}}
                     <button type="button" class="Close" data-dismiss="alert" alert-label="Close"><span aria-hidden="true">&times;</span></button>
                     
                    </div>
                    @endif

                    <div class="form-row">
                          <div class="col-md-6 mb-3">
                            <label for="validationDefault01">Nombre</label>
                          <input type="text" class="form-control" id="validationDefault01" value="{{auth()->user()->name}}" disabled="disabled" required>
                          </div>
                          <div class="col-md-6 mb-3">
                            <label for="validationDefault02">Apellido Paterno</label>
                            <input type="text" class="form-control" id="validationDefault02" value="{{auth()->user()->apellidopat}}" disabled="disabled" required>
                          </div>
                        </div>

                        <div class="form-row">
                          <div class="col-md-6 mb-3">
                            <label for="validationDefault01">Apellido Materno</label>
                          <input type="text" class="form-control" id="validationDefault01" value="{{auth()->user()->apellidomat}}" disabled="disabled" required>
                          </div>
                          <div class="col-md-6 mb-3">
                            <label for="validationDefault02">Correo electrónico</label>
                            <input type="email" class="form-control" id="validationDefault02" value="{{auth()->user()->email}}" disabled="disabled" required>
                          </div>
                        </div>
                        <div class="form-row">
                          <div class="col-md-6 mb-3">
                            <label for="validationDefault01">CURP</label>
                          <input type="text" class="form-control" id="validationDefault01" value="{{auth()->user()->curp}}" disabled="disabled" required>
                          </div>
                          <div class="col-md-6 mb-3">
                            <label for="validationDefault02">Telefono</label>
                            <input type="tel" class="form-control" id="validationDefault02" value="{{auth()->user()->telefono}}"  disabled="disabled" required>
                          </div>
                        </div>
                        
                        <div class="form-group">
                          <div class="form-check">
                            
                          </div>
                        </div>
                        <a class="btn btn-success btn-lg btn-block" href="{{ route('usuario.edit', auth()->id() ) }}">Editar Perfil</a>
                    
                </div>
            </div>
        </div>
    </div>
</div>


@endsection

resources/views/layouts/app.blade.php
<style>
    .imagen1{
    width: 250px;
    height: px;
}
</style>
<!DOCTYPE doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
    <head>
        <meta charset="utf-8">
            <meta content="width=device-width, initial-scale=1" name="viewport">
                <!-- CSRF Token -->
                <meta content="{{ csrf_token() }}" name="csrf-token">
                    <title>
                        {{ config('app.name', 'Laravel') }}
                    </title>
                    <!-- Scripts -->
                    <script defer="" src="{{ asset('js/app.js') }}">
                    </script>
                    <!-- Fonts -->
                    <link href="//fonts.gstatic.com" rel="dns-prefetch">
                        <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">
                            <link href="{{asset('css/bootstrap.min.css')}}" rel="stylesheet">
                                <link href="{{asset('css/estilos.css')}}" rel="stylesheet">
                                    <!-- Styles -->
                                    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
                                    </link>
                                </link>
                            </link>
                        </link>
                    </link>
                </meta>
            </meta>
        </meta>
    </head>
    <body>
        <div id="app">
            <nav class="navbar navbar-expand-md navbar-light bg-white shadow-sm">
                <div class="container">
                    <a class="navbar-brand" href="#">
                        <img alt="logo" class="imagen1" src="/images/seq2.png"/>
                    </a>
                    <button aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}" class="navbar-toggler" data-target="#navbarSupportedContent" data-toggle="collapse" type="button">
                        <span class="navbar-toggler-icon">
                        </span>
                    </button>
                    <div class="collapse navbar-collapse" id="navbarSupportedContent">
                        <!-- Left Side Of Navbar -->
                        <ul class="navbar-nav mr-auto">
                        </ul>
                        <!-- Right Side Of Navbar -->
                        <ul class="navbar-nav ml-auto">
                            <!-- Authentication Links -->
                            @guest
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('login') }}">
                                    Iniciar Sesión
                                </a>
                            </li>
                            @if (Route::has('register'))
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('register') }}">
                                    Registro
                                </a>
                            </li>
                            @endif
                        @else
                            <li class="nav-item dropdown">
                                <a aria-expanded="false" aria-haspopup="true" class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" id="navbarDropdown" role="button" v-pre="">
                                    {{ Auth::user()->name }}
                                    <span class="caret">
                                    </span>
                                </a>
                                <div aria-labelledby="navbarDropdown" class="dropdown-menu dropdown-menu-right">
                                    <a class="dropdown-item" href="{{ route('logout') }}" onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        Cerrar Sesión
                                    </a>
                                    <form action="{{ route('logout') }}" id="logout-form" method="POST" style="display: none;">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                            @endguest
                        </ul>
                    </div>
                </div>
            </nav>
            @auth
            <!--  // Si el usuario esta identificado... -->
            <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
                <a class="navbar-brand" href="#">
                    IDEPMSN
                </a>
                <button aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation" class="navbar-toggler" data-target="#navbarNavDropdown" data-toggle="collapse" type="button">
                    <span class="navbar-toggler-icon">
                    </span>
                </button>
                <div class="collapse navbar-collapse" id="navbarNavDropdown">
                    <ul class="navbar-nav mx-auto">
                        <li class="nav-item active">
                            <a class="nav-link" href="{{route('home')}}">
                                Inicio
                                <span class="sr-only">
                                    (current)
                                </span>
                            </a>
                        </li>
                        <li class="nav-item dropdown">
                            <a aria-expanded="false" aria-haspopup="true" class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" id="navbarDropdownMenuLink">
                                Trámites
                            </a>
                            <div aria-labelledby="navbarDropdownMenuLink" class="dropdown-menu">
                                <a class="dropdown-item" href="">
                                    Escuela Superior
                                </a>
                                <a class="dropdown-item" href="#">
                                    Escuela Media Superior
                                </a>
                                <a class="dropdown-item" href="#">
                                    Escuela Normal
                                </a>
                            </div>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#">
                                Seguimiento
                            </a>
                        </li>
                    </ul>
                </div>
            </nav>
            @endauth
            <main class="py-4">
                @yield('content')
            </main>
        </div>
        <div class="espaciado">
        </div>
        
        <footer>
       
        <div class="container-footer-all">
         
             <div class="container-body">
 
                 <div class="colum1">
                     <h1>TRÁMITE NCORPORACIÓN DE ESCUELAS PARTICULARES</h1>
 
                     <p>OTORGAR RECONOCIMIENTOS DE VALIDEZ OFICIAL DE ESTUDIOS A ESCUELAS PARTICULARES PARA IMPARTIR EDUCACIÓN MEDIA SUPERIOR, SUPERIOR Y NORMALES.</p>
 
                 </div>
 
                 <div class="colum2">
 
                     <h1>Redes Sociales</h1>
 
                     <div class="row">
                    <a href="https://www.facebook.com/educacionqr/"><img src="{{asset('icon/facebook.png')}}"></a> 
                    <a href="https://www.facebook.com/educacionqr/"><label>Siguenos en Facebook</label></a>
                     </div>
                     <div class="row">
                        <a href="https://twitter.com/educacionqr/"><img src="{{asset('icon/twitter.png')}}"></a> 
                      <a href="https://twitter.com/educacionqr/"><label>Siguenos en Twitter</label></a> 
                     </div>
                 </div>
 
                 <div class="colum3">
 
                     <h1>Información de contacto</h1>
 
                     <div class="row2">
                         <img src="{{asset('icon/house.png')}}">
                         <label>Av. Insurgentes No. 600 - Col. Gonzalo Guerrero Teléfono : 01 (983) 83 - 507 - 70 C.P. 77020 - Chetumal, Quintana Roo</label>
                     </div>

                     <div class="row2">
                        <img src="{{asset('icon/smartphone.png')}}">
                        <label>(983) 83 5 07 70 </label>
                    </div>
                 </div>
 
             </div>
         
         </div>
         
         <div class="container-footer">
                <div class="footer">
                     <div class="copyright">
                         © 2020 Todos los Derechos Reservados | <a href="https://qroo.gob.mx/seq">SEQ</a>
                     </div>
 
                     <div class="information">
                         <a href="">Informacion Compañia</a> | <a href="">Privacion y Politica</a> | <a href="">Terminos y Condiciones</a>
                     </div>
                 </div>
 
             </div>
         
     </footer>
     
    </body>
</html>

resources/views/layouts/formatos.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
   
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">

    <title>Solicitud </title>
    @yield('htmlGen')
</head>
<body>
    <button type="button" class="btn btn-primary">Guardar</button>
    @yield('Contenido')
</body>
</html>

resources/views/users/edit.blade.php
@extends('layouts.app')

@section('content')

<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header"><h1>Información personal</h1></div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif
                    <form action="{{ route('usuario.update',auth()->id() ) }}" method="POST">
                        @csrf
                        @method('PUT')
                        <div class="form-row">
                          <div class="col-md-6 mb-3">
                            <label for="validationDefault01">Nombre</label>
                          <input type="text" name="name" class="form-control" id="validationDefault01" value="{{auth()->user()->name}}" required>
                          </div>
                          <div class="col-md-6 mb-3">
                            <label for="validationDefault02">Apellido Paterno</label>
                            <input type="text" name="apellidopat"class="form-control" id="validationDefault02" value="{{auth()->user()->apellidopat}}" required>
                          </div>
                        </div>

                        <div class="form-row">
                          <div class="col-md-6 mb-3">
                            <label for="validationDefault01">Apellido Materno</label>
                          <input type="text" name="apellidomat" class="form-control" id="validationDefault01" value="{{auth()->user()->apellidomat}}" required>
                          </div>
                          <div class="col-md-6 mb-3">
                            <label for="validationDefault02">Correo electrónico</label>
                            <input type="email" name="email" class="form-control @error('email') is-invalid @enderror" id="validationDefault02" value="{{auth()->user()->email}}" required>
                            @error('email')
                            <span class="invalid-feedback" role="alert">
                                <strong>{{ $message }}</strong>
                            </span>
                        @enderror
                          </div>
                        </div>
                        <div class="form-row">
                            <div class="col-md-6 mb-3">
                              <label for="validationDefault01">CURP</label>
                            <input type="text" name="curp" class="form-control @error('curp') is-invalid @enderror" id="validationDefault01" value="{{auth()->user()->curp}}" required>
                                @error('curp')
                                <span class="invalid-feedback" role="alert">
                                    <strong>El CURP ya existe.</strong>
                                </span>
                            @enderror
                            </div>
                            <div class="col-md-6 mb-3">
                              <label for="validationDefault02">Telefono</label>
                              <input type="tel" name="telefono"class="form-control" id="validationDefault02" value="{{auth()->user()->telefono}}" required>
                            </div>
                          </div>
                        
                        <div class="form-group">
                          <div class="form-check">
                            
                          </div>
                        </div>
                        <button class="btn btn-success btn-lg btn-block">Guardar</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

@endsection